apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - name: backend-user
        image: sirsabek/udagram-api-user
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"  
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
      restartPolicy: Always